<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * `./yii message/extract @app/messages/i18n.php`
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detaild description for each parameter.
 */

return [
    'sourcePath'  => __DIR__ . '/../',
    'languages' => ['en-US', 'th-TH'],
    'translator' => 'Yii::t',
    'sort' => false,
    'removeUnused' => false,
    'only' => ['*.php'],
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/tests',
        '/vendor',
        '/themes',
    ],
    // 'format' => 'php',
    // 'messagePath' => __DIR__,
    // 'overwrite' => true,
     
    'format' => 'db',
    'db' => 'db',
    
    // 'format' => 'po',
    // 'catalog' => 'messages',
    // 'overwrite' => true,
    
    'ignoreCategories' => [],
];